root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api/"
bin = "./tmp/main"
include_ext = ["go", "html", "tmpl"]
exclude_dir = ["tmp", "vendor", "node_modules"]
include_dir = ["cmd", "internal", "migrations", "remote"]
delay = 500  # Reduced delay for faster response

[log]
time = true

[misc]
clean_on_exit = true