services:
  postgres:
    image: postgres:17.5-bookworm
    ports:
      - "5432:5432"
    env_file:
      - ../../dev.env
    volumes:
      - save_api_local_data:/var/lib/postgresql/data
    networks:
      - save_api_local_nw

networks:
  save_api_local_nw:
    external: true

volumes:
  save_api_local_data:
   